// React import
import React, { useState, useEffect } from 'react';
import AlertModal from '../modals/alertModal';
import SortByHeader from '@components/headerSort/sortByHeader';

const BackendIP = import.meta.env.VITE_BackendIP
const BackendPort = import.meta.env.VITE_BackendPort
const ApiAccess = import.meta.env.VITE_APIAccess
function Logs() {

    // UseStates for log data
    const [data, setData] = useState([]);
    const [tableHeaders, setTableHeaders] = useState([]);
    const [dataObtained, setDataObtained] = useState(false);
    const [dataFiltered, setFilteredData] = useState([]);

    //table sorting
    const [column, setColumn] = useState(null);
    const [sortOrder, setOrder] = useState('desc');
    

    // UseStates for date range
    const [startDate, setStartDate] = useState('');
    const [endDate, setEndDate] = useState('');

    //Modal things
    const [alertMessage, setAlertMessage] = useState("");
    const [isAlertModalOpen, setIsAlertModalOpen] = useState(false);

    // Map the headers to the data for the table
    const headerMapping = {
        "logID": "Log ID",
        "actorID": "Actor ID",
        "affectedOrder": "Affected Order",
        "actionLogged": "Action Logged",
        "timeLogged": "Time Logged"
    };

    // Get the logs
    const GetLogs = async () => {
        try {
            let end = endDate.toString() || null;

            // Call the API
            const response = await fetch('https://'+BackendIP+':'+BackendPort+'/api/Log/getlogs', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Key-Auth':ApiAccess


                },                    
                body: JSON.stringify({
                    StartDate: startDate.toString(),
                    EndDate: end
                }),
            });
            // Get the data out of the response
            const fetchedData = await response.json();

            // If there is an issue with the response, alert the user
            if(response.status != 200) {
                setAlertMessage(fetchedData.message);
                setIsAlertModalOpen(true);
                console.error(fetchedData.message);
                return;
            }

            if (fetchedData.data.length > 0) {
                // We got data, so transform it
                // This doesn't need to be he.decoded since it's generated by the system and therefore not including any "dangerous" characters
                const transformedData = fetchedData.data.map(item => {
                    return {
                        "Log ID": item.logID,
                        "Actor ID": item.actorID,
                        "Affected Order": item.affectedOrder,
                        "Action Logged": item.actionLogged,
                        "Time Logged": item.timeLogged
                    };
                });
                
                setData(transformedData);
                const keys = Object.keys(transformedData[0]);

                // Map the custom versions
                const customHeaders = keys.map(key => headerMapping[key] || key);
                setTableHeaders(customHeaders);
                setDataObtained(true);

            }
        } catch (error) {
            setAlertMessage("Error getting logs. Please try again.");
            setIsAlertModalOpen(true);
            console.error(error);
            setDataObtained(false);
        }
    }

    const handleSubmit = (e) => {
        e.preventDefault();
        GetLogs();
    }

    //function to handle sorting when a header is clicked
    const headerSort = (header,swap) => {

        //this sets a use state header so that when the page is updated it will re-sort

        //toggle sort order if clicking the same column, otherwise it will do ascending
        
        if (swap == true){
            let newSortOrder = 'asc';
            if (column === header && sortOrder === 'asc') {
                newSortOrder = 'desc';
            }
            setColumn(header);
            setOrder(newSortOrder);
            let sortedData = SortByHeader(data,header,newSortOrder);
            setFilteredData(sortedData);
        }
        else{
            let sortedData = SortByHeader(data,header,sortOrder);
            setColumn(header);
            setFilteredData(sortedData);

        }
    };
    
    return(

        <div>
            <div className='page-header-name'>Logs List</div>
            <hr/>

            <form onSubmit={handleSubmit}>
                <input type="date" required onChange={e => setStartDate(e.target.value)} style={{width:150}}/>
                <input type="date" onChange={e => setEndDate(e.target.value)} style={{width:150}} />
                <br/>
                <button type="submit">Get Logs</button>
            </form>

            <AlertModal
                isOpen={isAlertModalOpen}
                message={alertMessage}
                onClose={() => setIsAlertModalOpen(false)}
            />


            <br/><br/>

            {dataObtained && (
                <table>
                    <thead>
                        <tr>
                            {tableHeaders.map(header => (
                                <th key={header} onClick={() => headerSort(header,true)} style={{ cursor: 'pointer' }}>
                                    {header} {column === header ? (sortOrder === 'asc' ? '▲' : '▼') : ''}</th>
                            ))}
                        </tr>
                    </thead>
                    <tbody>
                        {data.map((item, index) => (
                            <tr key={index}>
                                {tableHeaders.map(header => (
                                    <td key={header}>{item[header]}</td>
                                ))}
                            </tr>
                        ))}
                    </tbody>
                </table>
            )}
        </div>

    )

}

export default Logs;